#!/usr/bin/env python3
"""boltwipe — NTAG424 DNA card verify/wipe driver over PC/SC.

Byte-exact port of the bolt-card-programmer app's NTag424.tsx secure
messaging, hardware-proven on 2026-08-25 (full wipe of a live card,
including recovery from an interrupted wipe). Reference APDUs for the
selftest are generated by bolt-card-programmer/refchangekey.js from the
app's own crypto (lesson B8: port wire-format crypto byte-for-byte, then
pin it with vectors from the original implementation).

Requires: pycryptodome, pyscard, any PC/SC reader (e.g. the esp32-ccid
firmware from this repo on a suitably-wired ESP32).

Usage:
  boltwipe.py selftest                          # offline vector check
  boltwipe.py verify --uid HEX --k1 HEX --k2 HEX
      Read-only: UID gate, NDEF URL, offline tap verdict (decrypt p under
      K1, CMAC-verify c under K2). Proves keys with ZERO card auth.
  boltwipe.py wipe --uid HEX --keys k0,k1,k2,k3,k4 [--resume-from N]
      EV2 auth with K0 (proved via GetCardUid) -> reset file settings ->
      ChangeKey 1..4 -> zeros -> ChangeKey 0 LAST -> clear NDEF + tail.
      --resume-from N: continue an interrupted wipe at key N (1-4, or 0).

Card-safety notes (bolty-rs docs/lessons-learned.md B6/B7):
  - Only failed AUTHENTICATION (91AE/91AD) feeds the lockout counter;
    in-session 911E does not. This driver never guesses keys.
  - A ChangeKey rejection for key N proves the staged old key N is wrong:
    STOP and re-source the keys (they may live beyond a truncated log line).
"""
import argparse
import binascii
import sys

from Crypto.Cipher import AES
from Crypto.Hash import CMAC

ZEROS = "00000000000000000000000000000000"

# --- reference vectors (synthetic keys; regenerate via refchangekey.js) ---
REF_SESSION = {
    "enc_key": "1234567890abcdef1234567890abcdef",
    "mac_key": "fedcba0987654321fedcba0987654321",
    "ti": "AABBCCDD",
    "ctr0": 3,
}
REF_KEYS = {
    "k0": "55555555555555555555555555555555",
    "k1": "11111111111111111111111111111111",
    "k2": "22222222222222222222222222222222",
    "k3": "33333333333333333333333333333333",
    "k4": "44444444444444444444444444444444",
}
REF_APDUS = {
    "FS_RESET": "905F00001902103f2395a25873b0635d930ad5776da7c96f2e0188d9fc9b00",
    "K1": "90C400002901b7a4406e4b51e939dcf27c307fc2cf18432f62b7fb9e30003ef6daae5f6c4dc684d49060a28cdbdd00",
    "K2": "90C400002902d1a53e1f93825b1e8d6d5e0a90c213847d52b2e9ee54e62bd5c290ee28d8c4f003c4d7617ba23cae00",
    "K3": "90C400002903ab57d46bc81862236fa2234099363a7f58b208d761c25af1bf97c53e8c40d956f71e19b3e37d9ebc00",
    "K4": "90C40000290434111e92114dd9730e82c726154cfda8a26a81d175678ac34ddf7685dcfb351902e71eef89540d7700",
    "K0": "90C400002900a0479ccd9d633e088c1eb9ce19057e44937bb99f6bf5b890fb07ee23727d1054c778a2e4a2e17fbc00",
}

# --- session state ---
S = {"ti": None, "enc_key": None, "mac_key": None, "ctr": 0}


def h2b(h): return binascii.unhexlify(h)
def b2h(b): return binascii.hexlify(b).decode()
def ecb_enc(key, data): return AES.new(h2b(key), AES.MODE_ECB).encrypt(data)
def ecb_dec(key, data): return AES.new(h2b(key), AES.MODE_ECB).decrypt(data)
def cmac_hex(key_hex, data_hex):
    c = CMAC.new(h2b(key_hex), ciphermod=AES)
    c.update(h2b(data_hex))
    return b2h(c.digest())
def trunc_mac(hex16):
    bb = h2b(hex16)
    return b2h(bytes(bb[i] for i in range(1, 16, 2)))
def ctr_lsb(n):
    f = format(n & 0xFFFF, "04x")
    return f[2:] + f[:2]


def iv_enc(cmd_ctr_hex):
    return b2h(ecb_enc(S["enc_key"], h2b("A55A" + S["ti"] + cmd_ctr_hex + "0000000000000000")))
def iv_resp(cmd_ctr_hex):
    return b2h(ecb_enc(S["enc_key"], h2b("5AA5" + S["ti"] + cmd_ctr_hex + "0000000000000000")))
def calc_mac(data_hex):
    return trunc_mac(cmac_hex(S["mac_key"], data_hex))
def pad_for_enc(data_hex, nbytes):
    if len(data_hex) < nbytes * 2:
        data_hex += "80"
        data_hex = data_hex.ljust(nbytes * 2, "0")
    return data_hex
def enc_data(padded_hex, ctr_hex):
    c = AES.new(h2b(S["enc_key"]), AES.MODE_CBC, h2b(iv_enc(ctr_hex)))
    return b2h(c.encrypt(h2b(padded_hex)))


def build_change_key(key_no, old_key, new_key, key_version="00"):
    ctrh = ctr_lsb(S["ctr"]); S["ctr"] += 1
    if key_no == "00":
        key_data = pad_for_enc(new_key + key_version, 32)
    else:
        oldnew_xor = b2h(bytes(i ^ j for i, j in zip(h2b(old_key), h2b(new_key))))
        import zlib
        crc = (zlib.crc32(h2b(new_key)) & 0xFFFFFFFF) ^ 0xFFFFFFFF  # CRC-32/JAMCRC (npm crc crcjam)
        crc_rev = b2h(h2b(format(crc, "08x"))[::-1])
        key_data = pad_for_enc(oldnew_xor + key_version + crc_rev, 32)
    enc = enc_data(key_data, ctrh)
    mac = calc_mac("C4" + ctrh + S["ti"] + key_no + enc)
    lc = format(len(enc) // 2 + len(mac) // 2 + 1, "02x")
    return "90C40000" + lc + key_no + enc + mac + "00"

def build_fs_reset():
    ctrh = ctr_lsb(S["ctr"]); S["ctr"] += 1
    enc = enc_data(pad_for_enc("40E0EE01FFFF", 16), ctrh)
    mac = calc_mac("5F" + ctrh + S["ti"] + "02" + enc)
    lc = format(len(enc) // 2 + len(mac) // 2 + 1, "02x")
    return "905F0000" + lc + "02" + enc + mac + "00"


def run_selftest() -> int:
    print("boltwipe selftest — synthetic reference vectors (see refchangekey.js)")
    S.update(ti=REF_SESSION["ti"], enc_key=REF_SESSION["enc_key"],
             mac_key=REF_SESSION["mac_key"], ctr=REF_SESSION["ctr0"])
    K = REF_KEYS
    mine = {
        "FS_RESET": build_fs_reset(),
        "K1": build_change_key("01", K["k1"], ZEROS),
        "K2": build_change_key("02", K["k2"], ZEROS),
        "K3": build_change_key("03", K["k3"], ZEROS),
        "K4": build_change_key("04", K["k4"], ZEROS),
        "K0": build_change_key("00", K["k0"], ZEROS),
    }
    ok = True
    for name, ref in REF_APDUS.items():
        match = mine[name] == ref
        print(f"  {name}: {'MATCH' if match else 'MISMATCH'}")
        if not match:
            ok = False
            print(f"    ref : {ref}")
            print(f"    mine: {mine[name]}")
    print("SELFTEST:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


# --- reader (only when a card mode is used) ---
def connect():
    from smartcard.System import readers
    rs = list(readers())
    if not rs:
        sys.exit("no PC/SC reader found")
    conn = rs[0].createConnection()
    conn.connect()
    print("reader:", rs[0])
    return conn

def apdu(conn, hexcmd):
    data, sw1, sw2 = conn.transmit(list(h2b(hexcmd)))
    return b2h(bytes(data)), "%02x%02x" % (sw1, sw2)

def send(conn, hexcmd, want="9100"):
    resp, code = apdu(conn, hexcmd)
    print("  >>", hexcmd[:64] + ("..." if len(hexcmd) > 64 else ""), "=>", code,
          resp[:48] + ("..." if len(resp) > 48 else ""))
    if want and code != want:
        raise RuntimeError(f"APDU failed: got {code} want {want} (resp {resp})")
    return resp, code


def get_version(conn):
    r1, _ = send(conn, "9060000000", want="91af")
    r2, _ = send(conn, "90AF000000", want="91af")
    r3, _ = send(conn, "90AF000000", want="9100")
    return r3[:14].lower()

def gate_uid(conn, uid):
    card = get_version(conn)
    print("card UID:", card)
    if card != uid.lower():
        sys.exit(f"ABORT: UID mismatch — expected {uid}, got {card}")

def read_ndef(conn):
    send(conn, "00A4040007D276000085010100", want="9000")
    send(conn, "00A4000002E10300", want="9000")
    send(conn, "00A4000002E10400", want="9000")
    out = ""
    for off in range(0, 240, 16):
        r, code = apdu(conn, "00B0" + format(off, "04x") + "10")
        out += r
        if code != "9000" or len(r) < 32:
            break
    return out

def auth_ev2_first(conn, key_no, key_hex):
    send(conn, "00A4040007D276000085010100", want="9000")
    S.update(ti=None, enc_key=None, mac_key=None); S["ctr"] = 0
    r, _ = send(conn, "9071000005" + key_no + "0300000000", want="91af")
    rnd_b = b2h(ecb_dec(key_hex, h2b(r)))
    rnd_a = b2h(__import__("os").urandom(16))
    payload = AES.new(h2b(key_hex), AES.MODE_CBC, b"\x00" * 16).encrypt(
        h2b(rnd_a + rnd_b[2:] + rnd_b[:2]))
    r2, _ = send(conn, "90AF000020" + b2h(payload) + "00", want="9100")
    dec_hex = b2h(AES.new(h2b(key_hex), AES.MODE_CBC, b"\x00" * 16).decrypt(h2b(r2)))
    S["ti"] = dec_hex[:8]
    x = bytes(i ^ j for i, j in zip(h2b(rnd_a[4:16]), h2b(rnd_b[0:12])))
    sv_post = rnd_a[:4] + b2h(x) + rnd_b[12:32] + rnd_a[16:32]
    S["enc_key"] = cmac_hex(key_hex, "A55A00010080" + sv_post)
    S["mac_key"] = cmac_hex(key_hex, "5AA500010080" + sv_post)
    S["ctr"] = 0
    ctrh = ctr_lsb(S["ctr"]); S["ctr"] += 1
    mac = trunc_mac(cmac_hex(S["mac_key"], "51" + ctrh + S["ti"]))
    ru, _ = send(conn, "9051000008" + mac + "00", want="9100")
    dec_uid = AES.new(h2b(S["enc_key"]), AES.MODE_CBC,
                      h2b(iv_resp(ctr_lsb(S["ctr"])))).decrypt(h2b(ru[:-16]))
    return b2h(dec_uid)[:14]

def change_key(conn, key_no, old_key, new_key):
    send(conn, build_change_key(key_no, old_key, new_key))

def reset_file_settings(conn):
    send(conn, build_fs_reset())

def set_ndef(conn, msg_hex):
    send(conn, "00A4040007D276000085010100", want="9000")
    send(conn, "00A4000002E10300", want="9000")
    send(conn, "00A4000002E10400", want="9000")
    send(conn, "00D60000" + format(len(msg_hex) // 2 + 2, "02x")
         + format(len(msg_hex) // 2, "04x") + msg_hex, want="9000")

def zero_ndef_tail(conn):
    # hardware-proven: write 0..127 (empty-URI NDEF + zeros), then 128..255 (stale URL tail)
    send(conn, "00A4040007D276000085010100", want="9000")
    send(conn, "00A4000002E10300", want="9000")
    send(conn, "00A4000002E10400", want="9000")
    send(conn, "00D60000" + "80" + "0005d1010155" + "00" * 121, want="9000")
    send(conn, "00D60080" + "80" + "00" * 128, want="9000")


def verdict_for(url, uid, k1, k2):
    import re
    m = re.search(r"p=([0-9A-Fa-f]{16,64})&c=([0-9A-Fa-f]{8,32})", url)
    if not m:
        return [f"no p=/c= in URL: {url[:100]}"]
    p_hex, c_hex = m.group(1).lower(), m.group(2).lower()
    try:
        dec_hex = b2h(ecb_dec(k1, h2b(p_hex[:32])))
    except Exception as e:
        return [f"p decrypt error: {e}"]
    if not dec_hex.startswith("c7" + uid.lower()):
        return ["p does not decrypt to this card's UID under the provided K1"]
    ctr_hex = dec_hex[16:22]
    k_sdm = cmac_hex(k2, "3cc300010080" + uid.lower() + ctr_hex)
    good = trunc_mac(cmac_hex(k_sdm, "")) == c_hex
    return [f"VERDICT: {'*** KEYS CONFIRMED (K1/K2) ***' if good else 'UID decrypts but CMAC mismatch'} ctr={ctr_hex}"]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="mode", required=True)
    sub.add_parser("selftest")
    v = sub.add_parser("verify")
    v.add_argument("--uid", required=True)
    v.add_argument("--k1", required=True)
    v.add_argument("--k2", required=True)
    w = sub.add_parser("wipe")
    w.add_argument("--uid", required=True)
    w.add_argument("--keys", required=True, help="k0,k1,k2,k3,k4 (hex, comma-separated)")
    w.add_argument("--resume-from", type=int, choices=[0, 1, 2, 3, 4],
                   help="continue interrupted wipe at this key number")
    args = ap.parse_args()

    if args.mode == "selftest":
        return run_selftest()

    conn = connect()
    try:
        gate_uid(conn, args.uid)

        if args.mode == "verify":
            ndef_hex = read_ndef(conn)
            txt = bytes.fromhex(ndef_hex).decode("latin1")
            print("NDEF:", txt[:250].replace("\x00", "."))
            import re
            m = re.search(r"[a-z]+://[!-~]+", txt)
            for line in verdict_for(m.group(0) if m else "", args.uid, args.k1, args.k2):
                print(line)
            return 0

        keys = dict(zip(("k0", "k1", "k2", "k3", "k4"),
                        (k.strip().lower() for k in args.keys.split(","))))
        if any(len(k) != 32 for k in keys.values()):
            sys.exit("keys must be five 32-hex-char values")
        print(f"wiping {args.uid} (resume-from={args.resume_from})")
        uid = auth_ev2_first(conn, "00", keys["k0"])
        print("AUTH OK, session UID:", uid)
        if args.resume_from is None or args.resume_from > 0:
            # full run: reset file settings first; resume at key N skips earlier ones
            if args.resume_from is None:
                reset_file_settings(conn)
                print("file settings reset")
            for n in range(args.resume_from or 1, 5):
                change_key(conn, format(n, "02x"), keys[f"k{n}"], ZEROS)
                print(f"key {n:02d} -> zeros")
        change_key(conn, "00", keys["k0"], ZEROS)
        print("key 00 -> zeros")
        set_ndef(conn, "d101015500")
        zero_ndef_tail(conn)
        print("NDEF cleared + tail zeroed")
        print("WIPE COMPLETE")
        return 0
    finally:
        conn.disconnect()


if __name__ == "__main__":
    sys.exit(main())
